# Generated by Django 4.1.5 on 2023-01-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_course_slug_alter_document_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_file_viewer_background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('background_files', models.ImageField(upload_to='documents/background_files/')),
                ('document_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_file_viewer',
            field=models.ManyToManyField(related_name='Document_file_viewer_background', to='api.document_file_viewer_background'),
        ),
    ]
