# Generated by Django 4.1.5 on 2023-01-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_background_files_document_file_viewer_background_background_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_file_viewer',
        ),
        migrations.DeleteModel(
            name='Document_file_viewer_background',
        ),
    ]
