# Generated by Django 4.1.5 on 2023-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_document_document_file_viewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.FileField(upload_to='thumbnail/'),
        ),
    ]
