# Generated by Django 4.1.5 on 2023-01-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_document_key_wors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='key_wors',
        ),
    ]
