# Generated by Django 4.1.5 on 2023-01-26 01:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('api', '0014_remove_document_key_wors'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='key_wors',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
