# Generated by Django 4.1.5 on 2023-01-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_document_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='key_wors',
            new_name='key_words',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
    ]
